[project]
name = "text-adventure-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.120.2",
    "google-generativeai>=0.8.5",
]
